#+TITLE: Contributing with Markdown
#+AUTHOR: Mathieu Marques

** File Structure

Content consists of chapters and articles under =markdown/=. The chapters are
considered /timeless/ and are the content that should be kept up to date to
account for meta shifts and bannings. Articles on the other hand are dated
content.

- =articles/= ::
  Dated reports and theories.
- =chapters/= ::
  Most of the content goes there, organized in =ddeft/=, =ddft/= and =meandeck/=
  chapters. There's also =appendices/= for general-purposed resources.
- =partials/= ::
  Static content within the Wiki comes from those partials, this avoids having
  to maintain content within code.

** Scryfall

In some contexts, you can refer to card names within Markdown. To ease the
writing process and reduce typos, a number of shorthands for card names can be
found [[./tools/game/constants/Cards.ts][here]].

For parts where you query card imagery, you can optionally provide a specific
set using the 3-letters set code. By default, the first print for the card is
used.

#+BEGIN_SRC
DD | SLD
#+END_SRC

For instance, the above query will scry for /Doomsday/ from the /Secret Lair
Drop/ set. To identify the right code for your set, inspect the links at
[[https://scryfall.com/sets]].

In some specific cases, you will want to specify a collector number.This can be
achieved by suffixing the corresponding number. This is useful for sets with
multiple printings of the same card.

#+BEGIN_SRC
Duress | STA | 92
#+END_SRC

** Tables of Content

An automatic table of content can be inserted in Markdown documents with an
empty level 2 heading that reads exactly =Table of Contents=. Leave that heading
empty since none of its content will be rendered.

The table will look for level 2 and 3 headings in the whole document and render
as a numbered list of anchor links for each of them.

** Custom Directives

A number of custom directives are parsed within Markdown content. For the
technicalities, the supported specifications for directives in Markdown are
presented
[[https://talk.commonmark.org/t/generic-directives-plugins-syntax/444][here]].

The following sections will assume you know of /inline/, /leaf/ and /container/
directives.

- Inline directives (single colon =:=) ::
  Inline markup where the text does not create a new paragraph.
- Leaf directives (double colons =::=) ::
  Create a new paragraph but accept no children within.
- Container directives (a pair of triple or more colons =:::=) ::
  Also create a new paragraph but accept children between the opening and
  closing pairs. It is possible to nest /container/ directives by using more
  than 3 colons.

See [[https://doomsday.wiki/markdown]] for examples of the below features.

*** Inline Card Links

You can insert inline Scryfall links for cards using the following syntax:

#+BEGIN_SRC markdown
:card[Brainstorm]
#+END_SRC

This will render an inline link reading "Brainstorm" and pointing to
[[https://scryfall.com/search?q=!Brainstorm]].

*** Decklists

You can add decklists within your Markdown content, they will be rendered as a
collapsible block. Decklist files are located under =decklists/= and should be
dated using a =[year]/[month]/[day]/file.txt= (or =[year]/[month]/file.txt= when
you don't have the exact date) convention if able. Follow the existing structure
as an example. As an exception, decklist files found directly under =decklists/=
are used in non-dated content to ease maintenance eg. in chapters.

#+BEGIN_SRC markdown
::decklist{path=path/to/decklist/sans/extension}
#+END_SRC

The content of decklist files supports title, authors and colors metadata.
Columns in the rendered decklist can be created using blank lines. The following
example shows how to write a decklist file with 2 columns of cards and a 3rd
column for the sideboard. In doubt, follow existing conventions.

#+BEGIN_SRC text
// Title: Dummy Example
// Authors: Author One, Author Two
// Colors: {U}{B}{R}
4 Dark Ritual
4 Doomsday

4 Polluted Delta
1 Island

// Sideboard
1 Duress
#+END_SRC

For more details about color symbols, see the [[#mana][Mana section]].

*** Spoils Calculator

Insert a /Spoils of the Vault/ widget to let the reader run success rate
simulations directly within the Markdown content.

#+BEGIN_SRC markdown
::spoils
#+END_SRC
