#+TITLE: Contributing with Markdown
#+AUTHOR: Mathieu Marques

** File Structure

Content consists of chapters and articles under =markdown/=. The chapters are
considered /timeless/ and are the content that should be kept up to date to
account for meta shifts and bannings. Articles on the other hand are dated
content.

- =archive/= ::
  Old content that no longer presents relevance due to bannings or else.
- =articles/= ::
  Dated reports and theories.
- =chapters/= ::
  Most of the content goes there, organized in =ddeft/=, =ddft/= and =meandeck/=
  chapters. There's also =appendices/= for general-purposed resources.
- =partials/= ::
  Static content within the Wiki comes from those partials, this avoids having
  to maintain content alongside code.

** General Markdown Conventions

- Fill your paragraphs to 80 columns
- If your title makes the frontmatter data longer than 80 columns, think of a
  better heading for your document. In addition to annoy users with
  terminal-based clients, it also might not look as good in the homepage where
  article cards are rendered with their corresponding title
- Heading levels start at 2 in order to account for the title found in the
  Markdown frontmatter
- Don't use unicode quote characters eg. =‘’= and =“”=. They might not render
  properly for everyone so ASCII quotes eg. ='= and ="= should be preferred
- A colon right in front of a word will be interpreted as a /directive/ so make
  sure you have a space right after =:= when it is used as punctuation
- A dot right after a number character ie. when you end your sentence with a
  digit renders as a numbered list item. To avoid this behavior, escape the dot
  with a backslash: =[...] you might want all 4\.=
- Depending on one's Markdown client, a dot at the end of a link can be
  considered part of said link eg. when you end your sentences with a link you
  should add a space before the final dot

** Scryfall

In some contexts, you can refer to card names within Markdown. To ease the
writing process, a number of shorthands for card names can be found
[[./src/tools/scryfall/cards.ts][here]].

Optionally, provide a specific set for the representation using the 3-letters
set code. By default, the first print for the card is used.

#+BEGIN_SRC
Full Card Name | SET
#+END_SRC

For instance, =DD | WTH= will scry for /Doomsday/ in the /Weatherlight/ set. To
identify the right code for your set, inspect the links at
https://scryfall.com/sets .

In some specific cases, you will want to specify a collector number. This can be
achieved by suffixing the corresponding number. For instance:

#+BEGIN_SRC
Duress | STA | 92
#+END_SRC

** Frontmatter

Chapter document can take advantage of a front section called /frontmatter/ in
Markdown parlance. It should start with a triple-dash lines and end with
another. Within that section, a body of YAML metadata can be written.

- =order= ::
  A number to specificy the order of your chapter in its accordion within the
  sidebar. By default chapters are alpha-sorted using their slug (their path).
- =title= (mandatory) ::
  A string for your chapter title. Wrap it with double quotes ="= to allow
  special characters within such as =:= and ='=.

Articles don't have an =order= property but support other fields. Use other
existing articles for inspiration.

- =authors= ::
  Comma-separated list of authors that you want to credit for the article.
- =banner= (mandatory) ::
  Set a banner for the article to display in the homepage as well as at the top
  of the article in its own page. Scryfall syntax is supported.
- =kind= (mandatory) ::
  A kind symbol. Available values can be found in the keys at
  [[src/tools/markdown/constants/Kind.ts][Kind.ts]]
- =tags= ::
  An array of tag symbols. Available values can be found in the keys at
  [[src/tools/markdown/constants/Tag.ts][Tag.ts]]
- =title= (mandatory) ::
  A string for your article title. Wrap it with double quotes ="= to allow
  special characters within such as =:= and ='=.

** Tables of Content

An automatic table of content can be inserted in Markdown documents with an
empty level 2 heading that reads exactly =Table of Contents=. Leave that heading
empty since all of its content will not be rendered.

The table will look for level 2 and 3 headings in the whole document and render
as a numbered list of anchor links for each of them.

** Custom Constructions

A number of custom directives are parsed within Markdown content. For the
technicalities, the supported specifications for directives in Markdown are
presented
[[https://talk.commonmark.org/t/generic-directives-plugins-syntax/444][here]].

*** Inline Card Links

You can insert inline Scryfall links for cards using the following syntax:

#+BEGIN_SRC markdown
:card[Brainstorm]
#+END_SRC

This will render an inline link reading "Brainstorm" and pointing to
https://scryfall.com/search?q=!"Brainstorm" .

*** Card Rows

Use this directive to render card images within your Markdown content. Scryfall
queries are supported and you can specify which set to use.

By default rows of cards are rendered with the =CENTERED= variant but you can
specify the variant with the =variant= keyword.

*Centered* rows allocate 25% of the available width for each image. Beyond 4
cards, images start shrinking so that they all fit on one line.

#+BEGIN_SRC markdown
:::row{variant=CENTERED}
- Lion's Eye Diamond | MIR
- Edge of Autumn
- Thassa's Oracle
:::
#+END_SRC

*Pile* rows are rendered using a unique style to make them stand out to the
reader. In addition, they use a fixed width of 20% for each image.

#+BEGIN_SRC markdown
:::row{variant=PILE}
- Lion's Eye Diamond | MIR
- Edge of Autumn
- Ideas Unbound
- Lotus Petal
- Thassa's Oracle
:::
#+END_SRC

*** Decklists

You can add decklists within your Markdown content, they will be rendered as a
collapsible block. Decklist files are located under =decklists/= and should be
dated using a =[year]/[month]/[day]/file.txt= (or =[year]/[month]/file.txt= when
you don't have the exact date) convention if able. Follow the existing structure
as an example. As an exception, decklist files found directly under =decklists/=
are used in non-dated content to ease maintenance eg. in chapters.

#+BEGIN_SRC markdown
::decklist{path=path/to/decklist/sans/extension}
#+END_SRC

The content of decklist files supports title, authors and colors metadata.
Columns in the rendered decklist can be created using blank lines. The following
example shows how to write a decklist file with 2 columns of cards and a 3rd
column for the sideboard. In doubt, follow existing conventions.

#+BEGIN_SRC text
// Title: Dummy Example
// Authors: Author One, Author Two
// Colors: {U}{B}{R}
4 Dark Ritual
4 Doomsday

4 Polluted Delta
1 Island

// Sideboard
1 Duress
#+END_SRC

For more details about color symbols, see the Mana section.

*** Media Embeds

Media embeds are also supported:

For a *SoundCloud* widget, use the following directive and provide its URL.

#+BEGIN_SRC markdown
::soundcloud{url=https://soundcloud.com/ddftwiki/a-history-of-doomsday}
#+END_SRC

For a *YouTube* widget, provide the ID typically found in the URL behind the =v=
parameter in the address bar.

#+BEGIN_SRC markdown
::youtube{id=3LLIFHv5kbo}
#+END_SRC

*Twitter* embeds have been removed from the Wiki due to lacking implementation
and security issues. They may or may not come back in the future.

*** Accordions

Collapsible blocks can be stacked against one another or used alone. Provide a
title for the CTA as well as a relative path to the Markdown partial to insert
in the accordion.

Do not specify the extension for the partial, =.md= is always assumed.

#+BEGIN_SRC markdown
::accordion[Click to expand]{path=path/to/partial/one/sans/extension}
::accordion[Click to expand]{path=path/to/partial/two/sans/extension}
#+END_SRC

** Mana

You can inline mana symbols in Markdown as well as in decklist blocks. When used
collectively, for instance to indicate the color identity of an archetype, use
the same order as found on the back of a /Magic: the Gathering/ card. This makes
searching for guilds and clans much easier later on. As an exception to this
rule and when referring to Doomsday colors, start with blue and black as it
makes it easier for the eyes to parse quickly the differences from one list to
the next.

The syntax that was followed during implementation can be found
[[https://mana.andrewgioia.com/icons.html][here]]. Currently only the mana costs
are implemented but loyalty and color indicators may come soon :tm:.
