#+TITLE: Contributing with Code
#+AUTHOR: Mathieu Marques

** Coding Conventions

*** TypeScript

- Respect existing conventions
- Respect the =eslint= configuration
- Respect the =prettier= configuration

A commit hook exists to check for ESLint errors and warnings to validate your
commits. It only validates the content of your commits.

*** Styles

Prefer the component styling properties when it makes sense, or the =sx=
property from =@mui/system= otherwise.

** TODO Commit Conventions

/Work in progress/

- Branch name
- Commit hooks
- Commit naming
- Pull request naming

** TODO Scryfall Cache

** Mocks

In order to both reduce the strain on Scryfall's API and allow offline
development, various mocks were set up. See =src/mocks/handlers.ts= for their
implementations and payloads.

See [[#environment-variables][#Environment Variables]] to disable the mocks.

** TODO Tests

/Work in progress/

- =jest=
- =react-testing-library=
- Coverage report

** Environment Variables

- =SCRYFALL_DEBUG= ::
  Whether the Scryfall caching server should output more logs.

You can overwrite their respective value, by creating a new =.env.local= at the
root of the project.
