/** List of default preferred sets for given card names. */
export const SETS: Record<string, string> =
  // prettier-ignore
  {
  'Brainstorm': 'MMQ',
  'Island':     'UNH',
  'Swamp':      'UNH',
};

/** Commonly used acronyms. */
export const SHORTHANDS: Record<string, string> =
  // prettier-ignore
  {
  AD:   'Abrupt Decay',
  AoI:  'Act on Impulse',
  BS:   'Brainstorm',
  BW:   'Burning Wish',
  CB:   "Conjurer's Bauble",
  CR:   'Cabal Ritual',
  CT:   'Cabal Therapy',
  CoS:  'Cavern of Souls',
  CoV:  'Chain of Vapor',
  Con:  'Consider',
  DA:   'Deep Analysis',
  DD:   'Doomsday',
  DR:   'Dark Ritual',
  DW:   'Divining Witch',
  Dur:  'Duress',
  EF:   'Experimental Frenzy',
  ET:   'Echoing Truth',
  Em:   'Emrakul, the Aeons Torn',
  EoA:  'Edge of Autumn',
  EoE:  'Echo of Eons',
  EtW:  'Empty the Warrens',
  FoN:  'Force of Negation',
  FoW:  'Force of Will',
  GP:   'Gitaxian Probe',
  IC:   'Infernal Contract',
  IU:   'Ideas Unbound',
  LDV:  "Lim-Dul's Vault",
  LED:  "Lion's Eye Diamond",
  LM:   'Laboratory Maniac',
  LP:   'Lotus Petal',
  Mm:   'Manamorphose',
  PT:   'Personal Tutor',
  Pdt:  'Predict',
  PiF:  'Past in Flames',
  Pnd:  'Ponder',
  PoN:  'Pact of Negation',
  Pre:  'Preordain',
  REB:  'Red Elemental Blast',
  RiP:  'Rest in Peace',
  SE:   'Surgical Extraction',
  SI:   'Shelldock Isle',
  SW:   'Street Wraith',
  SdT:  "Sensei's Divining Top",
  SotV: 'Spoils of the Vault',
  StP:  'Swords to Plowshares',
  TO:   "Thassa's Oracle",
  TW:   'Three Wishes',
  ToA:  'Tendrils of Agony',
  Tsz:  'Thoughtseize',
  VoS:  'Veil of Summer',
};
