name: Release

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: push

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm lint

  tests:
    name: Tests ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: pnpm test:coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        if: ${{ !cancelled() }}
        with:
          file-coverage-mode: all
          pr-number: auto
          threshold-icons: "{0: '🟠', 80: '🟡', 90: '⚪'}"
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

  preview:
    name: Preview
    needs: [lint]
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/deploy
        id: deploy
        with:
          environment: preview
          token: ${{ secrets.VERCEL_TOKEN }}
      - uses: ./.github/actions/comment
        if: ${{ !cancelled() }}
        with:
          token: ${{ github.token }}
          url: ${{ steps.deploy.outputs.url }}

  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [preview, tests]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/deploy
        with:
          environment: production
          token: ${{ secrets.VERCEL_TOKEN }}
